//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBUZhilishnikKuncevo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int id { get; set; }
        public string city { get; set; }
        public string area { get; set; }
        public string street { get; set; }
        public string buildingNumber { get; set; }
        public string buildingCorpse { get; set; }
        public int entranceNumber { get; set; }
        public int floorNumber { get; set; }
        public int apartmentNumber { get; set; }
    
        public virtual Apartment Apartment { get; set; }
    }
}
